### ISSUE TITLE
原理是啥？发现微博的相册里面的确没有

### ISSUE THREAD

**Issue by hujy23** [fate-lovely/pic-on-weibo#1]
如图，好厉害

**Comment by cj1128** [comment]
这个接口`http://picupload.service.weibo.com/interface`是纯粹的图片上传接口，上传的图片返回结果就是一个pid，如果这个pid没有和微博相关联的话，就是野生的图片，你在微博里面什么都看不到的。

**Comment by hujy23** [comment]
好厉害！
