### ISSUE TITLE
插件转移

### ISSUE THREAD

**Issue by Gloduck** [fate-lovely/pic-on-weibo#2]
请问如果我想把这个插件搬到edge上使用需要做些什么操作呢？

**Comment by cj1128** [comment]
你好，这个插件本身只是一个普通的Web应用，只需要能够发起HTTP请求即可，不依赖Chrome API，所以迁移到Edge上应该是很容易的~
我没有Windows开发环境，也不用Edge，所以无法自己来做了，Edge有一个[工具](https://developer.microsoft.com/en-us/microsoft-edge/platform/documentation/extensions/guides/porting-chrome-extensions/)可以转换Chrome插件，希望对你有帮助~
