### ISSUE TITLE
接口失效 SyntaxError: Unexpected token < in JSON at position 4

### ISSUE THREAD

**Issue by catonisland** [fate-lovely/pic-on-weibo#3]
目前上传均返回异常
SyntaxError: Unexpected token < in JSON at position 4

**Comment by cj1128** [comment]
你好，这个问题是由于微博返回的数据结构改变导致的，但是我修复这个问题以后，发现微博的的图片上传接口变得十分不稳定了，经常性404。因此新开发了一个基于七牛的图床，[图床on七牛](https://github.com/fate-lovely/pic-on-qiniu)，更加好用~这个项目就此废弃了。

**Comment by cj1128** [comment]
@catonisland 你好，最近很多朋友反映七牛的配置有点繁琐，想继续使用微博图床，然后我发现微博接口又稳定了（= =）。所以我修复了之前的问题。欢迎继续使用。
