### ISSUE TITLE
Work文档 直接转换成 带外链的Word

### ISSUE THREAD

**Issue by Seifon** [fate-lovely/pic-on-weibo#5]
比如我们经常会复制一整篇Word文档，或者是网上看到的一篇文章转成MarkDown

如果里面有很多图片，就比较麻烦了。

所以希望能够粘贴一篇文章到这个插件里面，然后将转好的文档显示出来，这样会提高效率

**Comment by cj1128** [comment]
这个功能超出这个插件的范畴了😆，这个插件是利用微博的图片上传接口上传图片，你说的复制word文档然后转成Markdown什么的，需要找找看别的工具~我估计应该不好做，应为word的格式非常麻烦😊

**Comment by Seifon** [comment]
主要是转换Word里面的图片。不用关心Word排版什么的。
