### ISSUE TITLE
剪贴板不能识别png，jpeg等格式

### ISSUE THREAD

**Issue by Seifon** [fate-lovely/pic-on-weibo#6]
复制一个图片时，如果是png或者其它格式，在插件里面粘贴不了。

**Comment by cj1128** [comment]
这个我刚刚测试了，复制一个PNG图片，然后进入插件，复制上传，没有任何问题。能详细说一下怎么复现吗？

**Comment by Seifon** [comment]
我从本地的一个Word里面复制的一张图片，然后到插件中，粘贴不了

**Comment by cj1128** [comment]
从文件系统直接拖拽上传吧。我估计在word里面复制的时候，可能是word为了实现自己的一些功能，修改了内容的MIME，不再是`image/*`了，导致插件判断不是图片🙄。

**Comment by Seifon** [comment]
好的
