### ISSUE TITLE
后缀其实可以直接写成jpg或者gif的

### ISSUE THREAD

**Issue by Seifon** [fate-lovely/pic-on-weibo#7]
很多插件都是这样，直接给的是jpg后缀，如果是动图就gif。

因为微博会将其它格式的图片自动转成这两种。

**Comment by cj1128** [comment]
`微博会将其他格式的图片自动转成这两种`这个我没考证过，不太清楚，微博也没有文档说明。需要后缀有什么特别的理由吗？ 图片上传成功以后，一般都是用在Markdown文档中，或者论坛发帖，没有后缀应该是没有任何影响的~

**Comment by Seifon** [comment]
我批量下载到本地备份时，因为没有后缀，打开稍微有点麻烦。

**Comment by cj1128** [comment]
我无法确认微博是否真的将图片都转成了JPG和GIF，所以就不添加后缀了。至于你提到的这个问题，很好解决，一行脚本批量添加一下后缀就可以了。

```bash
for f in *; do
mv $f $f.jpg
done
```
