### ISSUE TITLE
希望能够增加   网页右键上传图片的功能

### ISSUE THREAD

**Issue by Seifon** [fate-lovely/pic-on-weibo#8]
如果下面这个插件那样

https://github.com/Aqours/Weibo-Picture-Store

它的右键上传图片也很溜，希望能够加到你的插件中

**Comment by cj1128** [comment]
右键上传图片的话，为什么不直接右键复制图片URL然后使用呢😄？是想利用微博图床加速图片访问吗？
这个插件我不想设计的很复杂，只要最基本的功能，上传图片，生成URL，然后贴到我的博客或者文章中去~

**Comment by Seifon** [comment]
那应该做强大点。复制一篇多图的文章，能直接转成带外链的文章。这样会提高很多效率啦。

**Comment by cj1128** [comment]
`复制一篇多图的文章，能直接转成带外链的文章`，要解决这个问题，分成以下几个步骤。
1. 首先需要解析文章（Word文档）
2. 获取其中的图片
3. 使用图床上传图片
4. 修改原始文章，将所有的图片改为URL链接

这完全偏离这个插件的功能了😅你自己可以试试做做看。

**Comment by Seifon** [comment]
我是小白，不会弄啊。所以就靠大神您了
