### ISSUE TITLE
为什么传的图是压缩过的？

### ISSUE THREAD

**Issue by kami233** [fate-lovely/pic-on-weibo#9]
这个传的图并不是真正的原图，比如500k的图传上去是200k，而从17uw.cn这网站传的却是真正的原图，500就是500，一分不差，到底是怎么回事，是代码出了问题吗

**Comment by kami233** [comment]
逛了一下，貌似就是这个[issues](https://github.com/suxiaogang/WeiboPicBed/issues/49#issue-183278590)里说的传的时候没有勾选“上传原图”，所以传上去的都是经过压缩的，也就是说没有加入勾选“上传原图”的代码，同样是lagar，但却不一样

**Comment by cj1128** [comment]
@kami233 
应该是默认的上传参数是开启压缩的，因为我一般是用来放在文章里，所以压缩是我需要的行为（压缩的效果还很不错~）。

我找个时间看看，能不能找到“上传原图”需要的参数，找到了我更新一下插件，提供一个“上传原图”的选项。
